CREATE TABLE MOVIES (
   MOVIE_ID int NOT NULL,
   MOVIE_TITLE varchar(100) NOT NULL,
  RELEASE_DATE DATE NOT NULL,
  PRICE MONEY NOT NULL,
  RATING DECIMAL NOT NULL,
  GENRE VARCHAR NULL,
  PRIMARY KEY (MOVIE_ID)
  );


  CREATE TABLE ORDERS (
      ORDERS_ID int NOT NULL,
    RENTAL_DATE DATE NOT NULL,
      RETURN_DATE DATE NOT NULL,
      MOVIE_ID int,
      NET_AMOUNT MONEY,
      DISCOUNT DECIMAL,
    GROSS_AMOUNT MONEY )NOT NULL,

    PRIMARY KEY (ORDERS_ID),
    FOREIGN KEY (MOVIE_ID) REFERENCES MOVIES(MOVIE_ID)

  );
